import { Metric } from './types';

export const METRICS_DATA: Metric[] = [
  {
    id: '1',
    name: 'Page Load Time (P95)',
    key: 'latency_p95_frontend',
    baseline: '1.2s',
    variant: '1.45s',
    delta: '+15.2%',
    deltaValue: 15.2,
    pValue: 0.001,
    power: 98,
    status: 'CRITICAL',
  },
  {
    id: '2',
    name: 'Purchase Conversion',
    key: 'conv_checkout_success',
    baseline: '4.5%',
    variant: '4.49%',
    delta: '-0.1%',
    deltaValue: -0.1,
    pValue: 0.45,
    power: 85,
    status: 'STABLE',
  },
  {
    id: '3',
    name: 'Error Rate (5xx)',
    key: 'http_server_errors',
    baseline: '0.02%',
    variant: '0.03%',
    delta: '+2.0%',
    deltaValue: 2.0,
    pValue: 0.08,
    power: 92,
    status: 'WARNING',
  },
  {
    id: '4',
    name: 'API Latency (Checkout)',
    key: 'api_checkout_post',
    baseline: '230ms',
    variant: '228ms',
    delta: '-0.8%',
    deltaValue: -0.8,
    pValue: 0.62,
    power: 90,
    status: 'STABLE',
  },
  {
    id: '5',
    name: 'Add to Cart Rate',
    key: 'event_add_cart',
    baseline: '12.5%',
    variant: '12.8%',
    delta: '+2.4%',
    deltaValue: 2.4,
    pValue: 0.04,
    power: 95,
    status: 'STABLE',
  },
  {
    id: '6',
    name: 'Bounce Rate',
    key: 'session_bounce',
    baseline: '45.2%',
    variant: '45.0%',
    delta: '-0.4%',
    deltaValue: -0.4,
    pValue: 0.71,
    power: 88,
    status: 'STABLE',
  },
];
